// source: src/modules/evrynet/evrynet.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var src_modules_warp_common_pb = require('../../../src/modules/warp/common_pb.js');
goog.object.extend(proto, src_modules_warp_common_pb);
goog.exportSymbol('proto.evrynet.EvrynetCredit', null, global);
goog.exportSymbol('proto.evrynet.GetBalanceRequest', null, global);
goog.exportSymbol('proto.evrynet.GetBalanceResponse', null, global);
goog.exportSymbol('proto.evrynet.GetNonceRequest', null, global);
goog.exportSymbol('proto.evrynet.GetNonceResponse', null, global);
goog.exportSymbol('proto.evrynet.GetWhitelistAssetsResponse', null, global);
goog.exportSymbol('proto.evrynet.StellarCredit', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evrynet.GetNonceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evrynet.GetNonceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evrynet.GetNonceRequest.displayName = 'proto.evrynet.GetNonceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evrynet.GetNonceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evrynet.GetNonceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evrynet.GetNonceResponse.displayName = 'proto.evrynet.GetNonceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evrynet.StellarCredit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.evrynet.StellarCredit.repeatedFields_, null);
};
goog.inherits(proto.evrynet.StellarCredit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evrynet.StellarCredit.displayName = 'proto.evrynet.StellarCredit';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evrynet.EvrynetCredit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.evrynet.EvrynetCredit.repeatedFields_, null);
};
goog.inherits(proto.evrynet.EvrynetCredit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evrynet.EvrynetCredit.displayName = 'proto.evrynet.EvrynetCredit';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evrynet.GetWhitelistAssetsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evrynet.GetWhitelistAssetsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evrynet.GetWhitelistAssetsResponse.displayName = 'proto.evrynet.GetWhitelistAssetsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evrynet.GetBalanceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evrynet.GetBalanceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evrynet.GetBalanceRequest.displayName = 'proto.evrynet.GetBalanceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.evrynet.GetBalanceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.evrynet.GetBalanceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.evrynet.GetBalanceResponse.displayName = 'proto.evrynet.GetBalanceResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evrynet.GetNonceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.evrynet.GetNonceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evrynet.GetNonceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetNonceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    evrynetaddress: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evrynet.GetNonceRequest}
 */
proto.evrynet.GetNonceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evrynet.GetNonceRequest;
  return proto.evrynet.GetNonceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evrynet.GetNonceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evrynet.GetNonceRequest}
 */
proto.evrynet.GetNonceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvrynetaddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evrynet.GetNonceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evrynet.GetNonceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evrynet.GetNonceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetNonceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvrynetaddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string evrynetAddress = 1;
 * @return {string}
 */
proto.evrynet.GetNonceRequest.prototype.getEvrynetaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.evrynet.GetNonceRequest} returns this
 */
proto.evrynet.GetNonceRequest.prototype.setEvrynetaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evrynet.GetNonceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.evrynet.GetNonceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evrynet.GetNonceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetNonceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    nonce: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evrynet.GetNonceResponse}
 */
proto.evrynet.GetNonceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evrynet.GetNonceResponse;
  return proto.evrynet.GetNonceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evrynet.GetNonceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evrynet.GetNonceResponse}
 */
proto.evrynet.GetNonceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNonce(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evrynet.GetNonceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evrynet.GetNonceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evrynet.GetNonceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetNonceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNonce();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string nonce = 1;
 * @return {string}
 */
proto.evrynet.GetNonceResponse.prototype.getNonce = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.evrynet.GetNonceResponse} returns this
 */
proto.evrynet.GetNonceResponse.prototype.setNonce = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.evrynet.StellarCredit.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evrynet.StellarCredit.prototype.toObject = function(opt_includeInstance) {
  return proto.evrynet.StellarCredit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evrynet.StellarCredit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.StellarCredit.toObject = function(includeInstance, msg) {
  var f, obj = {
    assetsList: jspb.Message.toObjectList(msg.getAssetsList(),
    src_modules_warp_common_pb.Asset.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evrynet.StellarCredit}
 */
proto.evrynet.StellarCredit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evrynet.StellarCredit;
  return proto.evrynet.StellarCredit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evrynet.StellarCredit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evrynet.StellarCredit}
 */
proto.evrynet.StellarCredit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new src_modules_warp_common_pb.Asset;
      reader.readMessage(value,src_modules_warp_common_pb.Asset.deserializeBinaryFromReader);
      msg.addAssets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evrynet.StellarCredit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evrynet.StellarCredit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evrynet.StellarCredit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.StellarCredit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAssetsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      src_modules_warp_common_pb.Asset.serializeBinaryToWriter
    );
  }
};


/**
 * repeated common.Asset assets = 1;
 * @return {!Array<!proto.common.Asset>}
 */
proto.evrynet.StellarCredit.prototype.getAssetsList = function() {
  return /** @type{!Array<!proto.common.Asset>} */ (
    jspb.Message.getRepeatedWrapperField(this, src_modules_warp_common_pb.Asset, 1));
};


/**
 * @param {!Array<!proto.common.Asset>} value
 * @return {!proto.evrynet.StellarCredit} returns this
*/
proto.evrynet.StellarCredit.prototype.setAssetsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.common.Asset=} opt_value
 * @param {number=} opt_index
 * @return {!proto.common.Asset}
 */
proto.evrynet.StellarCredit.prototype.addAssets = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.common.Asset, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.evrynet.StellarCredit} returns this
 */
proto.evrynet.StellarCredit.prototype.clearAssetsList = function() {
  return this.setAssetsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.evrynet.EvrynetCredit.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evrynet.EvrynetCredit.prototype.toObject = function(opt_includeInstance) {
  return proto.evrynet.EvrynetCredit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evrynet.EvrynetCredit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.EvrynetCredit.toObject = function(includeInstance, msg) {
  var f, obj = {
    assetsList: jspb.Message.toObjectList(msg.getAssetsList(),
    src_modules_warp_common_pb.Asset.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evrynet.EvrynetCredit}
 */
proto.evrynet.EvrynetCredit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evrynet.EvrynetCredit;
  return proto.evrynet.EvrynetCredit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evrynet.EvrynetCredit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evrynet.EvrynetCredit}
 */
proto.evrynet.EvrynetCredit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new src_modules_warp_common_pb.Asset;
      reader.readMessage(value,src_modules_warp_common_pb.Asset.deserializeBinaryFromReader);
      msg.addAssets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evrynet.EvrynetCredit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evrynet.EvrynetCredit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evrynet.EvrynetCredit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.EvrynetCredit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAssetsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      src_modules_warp_common_pb.Asset.serializeBinaryToWriter
    );
  }
};


/**
 * repeated common.Asset assets = 1;
 * @return {!Array<!proto.common.Asset>}
 */
proto.evrynet.EvrynetCredit.prototype.getAssetsList = function() {
  return /** @type{!Array<!proto.common.Asset>} */ (
    jspb.Message.getRepeatedWrapperField(this, src_modules_warp_common_pb.Asset, 1));
};


/**
 * @param {!Array<!proto.common.Asset>} value
 * @return {!proto.evrynet.EvrynetCredit} returns this
*/
proto.evrynet.EvrynetCredit.prototype.setAssetsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.common.Asset=} opt_value
 * @param {number=} opt_index
 * @return {!proto.common.Asset}
 */
proto.evrynet.EvrynetCredit.prototype.addAssets = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.common.Asset, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.evrynet.EvrynetCredit} returns this
 */
proto.evrynet.EvrynetCredit.prototype.clearAssetsList = function() {
  return this.setAssetsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.evrynet.GetWhitelistAssetsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evrynet.GetWhitelistAssetsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetWhitelistAssetsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    nativeasset: (f = msg.getNativeasset()) && src_modules_warp_common_pb.Asset.toObject(includeInstance, f),
    stellarcredit: (f = msg.getStellarcredit()) && proto.evrynet.StellarCredit.toObject(includeInstance, f),
    evrynetcredit: (f = msg.getEvrynetcredit()) && proto.evrynet.EvrynetCredit.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evrynet.GetWhitelistAssetsResponse}
 */
proto.evrynet.GetWhitelistAssetsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evrynet.GetWhitelistAssetsResponse;
  return proto.evrynet.GetWhitelistAssetsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evrynet.GetWhitelistAssetsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evrynet.GetWhitelistAssetsResponse}
 */
proto.evrynet.GetWhitelistAssetsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new src_modules_warp_common_pb.Asset;
      reader.readMessage(value,src_modules_warp_common_pb.Asset.deserializeBinaryFromReader);
      msg.setNativeasset(value);
      break;
    case 2:
      var value = new proto.evrynet.StellarCredit;
      reader.readMessage(value,proto.evrynet.StellarCredit.deserializeBinaryFromReader);
      msg.setStellarcredit(value);
      break;
    case 3:
      var value = new proto.evrynet.EvrynetCredit;
      reader.readMessage(value,proto.evrynet.EvrynetCredit.deserializeBinaryFromReader);
      msg.setEvrynetcredit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evrynet.GetWhitelistAssetsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evrynet.GetWhitelistAssetsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetWhitelistAssetsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNativeasset();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      src_modules_warp_common_pb.Asset.serializeBinaryToWriter
    );
  }
  f = message.getStellarcredit();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.evrynet.StellarCredit.serializeBinaryToWriter
    );
  }
  f = message.getEvrynetcredit();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.evrynet.EvrynetCredit.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.Asset nativeAsset = 1;
 * @return {?proto.common.Asset}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.getNativeasset = function() {
  return /** @type{?proto.common.Asset} */ (
    jspb.Message.getWrapperField(this, src_modules_warp_common_pb.Asset, 1));
};


/**
 * @param {?proto.common.Asset|undefined} value
 * @return {!proto.evrynet.GetWhitelistAssetsResponse} returns this
*/
proto.evrynet.GetWhitelistAssetsResponse.prototype.setNativeasset = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evrynet.GetWhitelistAssetsResponse} returns this
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.clearNativeasset = function() {
  return this.setNativeasset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.hasNativeasset = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional StellarCredit stellarCredit = 2;
 * @return {?proto.evrynet.StellarCredit}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.getStellarcredit = function() {
  return /** @type{?proto.evrynet.StellarCredit} */ (
    jspb.Message.getWrapperField(this, proto.evrynet.StellarCredit, 2));
};


/**
 * @param {?proto.evrynet.StellarCredit|undefined} value
 * @return {!proto.evrynet.GetWhitelistAssetsResponse} returns this
*/
proto.evrynet.GetWhitelistAssetsResponse.prototype.setStellarcredit = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evrynet.GetWhitelistAssetsResponse} returns this
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.clearStellarcredit = function() {
  return this.setStellarcredit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.hasStellarcredit = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EvrynetCredit evrynetCredit = 3;
 * @return {?proto.evrynet.EvrynetCredit}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.getEvrynetcredit = function() {
  return /** @type{?proto.evrynet.EvrynetCredit} */ (
    jspb.Message.getWrapperField(this, proto.evrynet.EvrynetCredit, 3));
};


/**
 * @param {?proto.evrynet.EvrynetCredit|undefined} value
 * @return {!proto.evrynet.GetWhitelistAssetsResponse} returns this
*/
proto.evrynet.GetWhitelistAssetsResponse.prototype.setEvrynetcredit = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evrynet.GetWhitelistAssetsResponse} returns this
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.clearEvrynetcredit = function() {
  return this.setEvrynetcredit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evrynet.GetWhitelistAssetsResponse.prototype.hasEvrynetcredit = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evrynet.GetBalanceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.evrynet.GetBalanceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evrynet.GetBalanceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetBalanceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountaddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    asset: (f = msg.getAsset()) && src_modules_warp_common_pb.Asset.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evrynet.GetBalanceRequest}
 */
proto.evrynet.GetBalanceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evrynet.GetBalanceRequest;
  return proto.evrynet.GetBalanceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evrynet.GetBalanceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evrynet.GetBalanceRequest}
 */
proto.evrynet.GetBalanceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountaddress(value);
      break;
    case 2:
      var value = new src_modules_warp_common_pb.Asset;
      reader.readMessage(value,src_modules_warp_common_pb.Asset.deserializeBinaryFromReader);
      msg.setAsset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evrynet.GetBalanceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evrynet.GetBalanceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evrynet.GetBalanceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetBalanceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountaddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAsset();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      src_modules_warp_common_pb.Asset.serializeBinaryToWriter
    );
  }
};


/**
 * optional string accountAddress = 1;
 * @return {string}
 */
proto.evrynet.GetBalanceRequest.prototype.getAccountaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.evrynet.GetBalanceRequest} returns this
 */
proto.evrynet.GetBalanceRequest.prototype.setAccountaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional common.Asset asset = 2;
 * @return {?proto.common.Asset}
 */
proto.evrynet.GetBalanceRequest.prototype.getAsset = function() {
  return /** @type{?proto.common.Asset} */ (
    jspb.Message.getWrapperField(this, src_modules_warp_common_pb.Asset, 2));
};


/**
 * @param {?proto.common.Asset|undefined} value
 * @return {!proto.evrynet.GetBalanceRequest} returns this
*/
proto.evrynet.GetBalanceRequest.prototype.setAsset = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.evrynet.GetBalanceRequest} returns this
 */
proto.evrynet.GetBalanceRequest.prototype.clearAsset = function() {
  return this.setAsset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.evrynet.GetBalanceRequest.prototype.hasAsset = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.evrynet.GetBalanceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.evrynet.GetBalanceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.evrynet.GetBalanceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetBalanceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    balance: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.evrynet.GetBalanceResponse}
 */
proto.evrynet.GetBalanceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.evrynet.GetBalanceResponse;
  return proto.evrynet.GetBalanceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.evrynet.GetBalanceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.evrynet.GetBalanceResponse}
 */
proto.evrynet.GetBalanceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBalance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.evrynet.GetBalanceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.evrynet.GetBalanceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.evrynet.GetBalanceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.evrynet.GetBalanceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBalance();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string balance = 1;
 * @return {string}
 */
proto.evrynet.GetBalanceResponse.prototype.getBalance = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.evrynet.GetBalanceResponse} returns this
 */
proto.evrynet.GetBalanceResponse.prototype.setBalance = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.evrynet);
